# Generated by Django 3.2.7 on 2021-10-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211018_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='isAGift',
        ),
        migrations.AddField(
            model_name='order',
            name='giftPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
