# Generated by Django 3.2.7 on 2021-10-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211018_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
