products = [
    {
        '_id': '1',
        'name': r'Retinol 0.5% in Squalane',
        'image': '/images/',
        'description':
        'This water-free solution contains 0.5% pure Retinol, an ingredient that can reduce the appearances of fine lines, of photo damage and of general skin aging.',
        'brand': 'The Ordinary',
        'category': 'Retinol',
        'price': 37,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Euk 134 0.1% ',
        'image': '/images/',
        'description':
        ' A formula that has been shown to reduce visible redness and protect against appearance of UV damage.',
        'brand': 'The Ordinary',
        'category': '',
        'price': 30,
        'countInStock': 0,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Salycilid Acid Masque 2%',
        'image': '/images/',
        'description':
        'This mask targets the removal of dead skin cells on the surface of oily and blemish-prone skin, with the purpose of revealing more radiant skin beneath.',
        'brand': 'The Ordinary',
        'category': '',
        'price': 45,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Niacinamide 10%+Zinc 1%',
        'image': '/images/',
        'description':
        'Niacinamide (vitamin B3) reduces the appearance of skin blemishes and congestion. A high 10 percent concentration of this vitamin is supported in the formula by zinc PCA to balance visible aspects of sebum activity.',
        'brand': 'The Ordinary',
        'category': '',
        'price': 37,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Hyaluronic acid 2%+B5',
        'image': '/images/',
        'description':
        'A moisturizing ingredient that occurs naturally in the skin. It attracts moisture to the skin and defends against dehydration over time. It replenishes the top layers of the skin, causing it to look smoother and plumper.',
        'brand': 'The Ordinary',
        'category': '',
        'price': 40,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'AHA 30% + BHA 2% Peeling Solution',
        'image': '/images/',
        'description':
        'This combined 32% AHA/BHA solution offers deeper exfoliation to help fight visible blemishes and for improved skin radiance. The',
        'brand': 'The Ordinary',
        'category': '',
        'price': 43,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'Azelaic Acid Suspension 10%',
        'image': '/images/',
        'description':
        'Brightens the skin tone while visibly improving uneven skin texture and reducing signs of congestion. It is a multi-functional ingredient that offers antioxidant support.',
        'brand': 'The Ordinary',
        'category': '',
        'price': 45,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
    {
        '_id': '8',
        'name': 'Glycolic Acid 7% Toning Solution',
        'image': '/images/',
        'description':
        'Glycolic Acid is an alpha hydroxy acid that exfoliates the skin. This 7% toning solution offers mild exfoliation for improved skin radiance and visible clarity.',
        'brand': 'The Ordinary',
        'category': '',
        'price': 45,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
]
